name: Stack Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nix
      run: sh <(curl -L https://nixos.org/nix/install) --daemon

    - name: Set up Nix
      run: nix-env -iA cachix -f https://cachix.org/api/v1/install
      env:
        CACHIX_USE: ghcjs

    - name: Install cachix cache
      run: cachix use nixpkgs-haskell

    - name: Build in Nix shell
      run: nix-shell --run "stack clean && stack build"

